//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationNine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_good { get; set; }
        public string good_article { get; set; }
        public string good_name { get; set; }
        public int edi_id { get; set; }
        public int price { get; set; }
        public int max_skid { get; set; }
        public int maker_id { get; set; }
        public int giver_id { get; set; }
        public int category_id { get; set; }
        public int act_skid { get; set; }
        public int kolvo { get; set; }
        public string discription { get; set; }
        public string image { get; set; }

        public string pic
        {
            get
            {
                if (String.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image))
                {
                    return "/systemimages/picture.png";
                }
                else
                {
                    return "/goodsimages/" + image;
                }
            }
        }

        public virtual Categories Categories { get; set; }
        public virtual Edis Edis { get; set; }
        public virtual Givers Givers { get; set; }
        public virtual Makers Makers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
