//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationNine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public string order_number { get; set; }
        public int order_good_id { get; set; }
        public int order_good_kolvo { get; set; }
        public System.DateTime order_date_order { get; set; }
        public System.DateTime order_date_delivery { get; set; }
        public int order_shop_id { get; set; }
        public int order_user_id { get; set; }
        public int order_code { get; set; }
        public int order_status { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Shops Shops { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
