//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationNine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_user { get; set; }
        public string user_surname { get; set; }
        public string user_name { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public int user_role_id { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
    }
}
